import Head from "next/head";
import "./globals.css";
import '../styles/fonts.css';
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ajay kumar Josyula",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charset="UTF-8" />
        <link rel="icon" href="/favicon/favicon.ico" sizes="any" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="/dist/output.css" rel="stylesheet" />
        <script src="https://cdn.emailjs.com/dist/email.min.js"></script>
       
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
