import Head from "next/head";
import "./globals.css";
import '../styles/fonts.css';
import { Inter } from "next/font/google";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ajay kumar Josyula",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charset="UTF-8" />
        <link rel="icon" href="/favicon/favicon.ico" sizes="any" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* <script src="https://cdn.emailjs.com/dist/email.min.js"></script>
        <script src="https://cdn.tailwindcss.com"></script> */}
   
    </Head>
    <Script
  src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"
  strategy="beforeInteractive"
/>
     
    <Script
          src="https://cdn.emailjs.com/dist/email.min.js"
          strategy="beforeInteractive" // or 'afterInteractive' depending on your use case
        />
    <Script
      src="https://cdn.tailwindcss.com"
      strategy="beforeInteractive" // or 'afterInteractive' depending on your use case
    />
      <body className={inter.className}>{children}</body>
    </html>
  );
}   